#!/bin/bash

if [[ `uname -s | grep MINGW` ]]; then
	CLASSPATH="bin;lib/eventbus.jar;lib/j-ogg-oggd.jar;lib/j-ogg-vorbisd.jar;lib/jME3-blender.jar;lib/jME3-core.jar;lib/jME3-desktop.jar;lib/jME3-effects.jar;lib/jME3-jbullet.jar;lib/jME3-jogg.jar;lib/jME3-lwjgl-natives.jar;lib/jME3-lwjgl.jar;lib/jME3-networking.jar;lib/jME3-niftygui.jar;lib/jME3-plugins.jar;lib/jME3-terrain.jar;lib/jME3-testdata.jar;lib/jbullet.jar;lib/jinput.jar;lib/lwjgl.jar;lib/nifty-default-controls.jar;lib/nifty-examples.jar;lib/nifty-style-black.jar;lib/nifty.jar;lib/stack-alloc.jar;lib/vecmath.jar;lib/xmlpull-xpp3.jar;lib/twitter4j-async-2.2.5.jar;lib/twitter4j-core-2.2.5.jar;lib/twitter4j-media-support-2.2.5.jar;lib/twitter4j-stream-2.2.5.jar";
else
	CLASSPATH="bin:lib/eventbus.jar:lib/j-ogg-oggd.jar:lib/j-ogg-vorbisd.jar:lib/jME3-blender.jar:lib/jME3-core.jar:lib/jME3-desktop.jar:lib/jME3-effects.jar:lib/jME3-jbullet.jar:lib/jME3-jogg.jar:lib/jME3-lwjgl-natives.jar:lib/jME3-lwjgl.jar:lib/jME3-networking.jar:lib/jME3-niftygui.jar:lib/jME3-plugins.jar:lib/jME3-terrain.jar:lib/jME3-testdata.jar:lib/jbullet.jar:lib/jinput.jar:lib/lwjgl.jar:lib/nifty-default-controls.jar:lib/nifty-examples.jar:lib/nifty-style-black.jar:lib/nifty.jar:lib/stack-alloc.jar:lib/vecmath.jar:lib/xmlpull-xpp3.jar:lib/twitter4j-async-2.2.5.jar:lib/twitter4j-core-2.2.5.jar:lib/twitter4j-media-support-2.2.5.jar:lib/twitter4j-stream-2.2.5.jar";
fi

if [ -f "sat.jar" ];
then
	java -jar sat.jar $@
else
	java -classpath $CLASSPATH sat.SAT $@
fi
